Repository michaelKurowski/lokim2, pull requests merged in 2018-05, with the labels that each got.

#30 #19 #39 Documentation of /Room namespace
  .gitignore
  .vscode/settings.json
  README.md
  src/server/.tests/generate-docs.spec.js
  src/server/.tests/ws-routes/controllers/Room.spec.js
  src/server/package-lock.json
  src/server/package.json
  src/server/protocol/protocol.json
  src/server/ws-routes/controllers/Room.js
  src/server/ws-routes/dataTypes.jsdoc
  src/server/ws-routes/initializeWebSocketRouting.js
  src/server/ws-routes/universalWebsocketEvents.jsdoc
Labels: PRIORITY, backend, documentation, enhancement

#27 #26 test for application startup
  .circleci/config.yml
  src/server/.tests/e2e/applicationRun.spec.js
  src/server/.tests/ws-routes/controllers/Room.spec.js
  src/server/config.json
  src/server/dbConnection.js
  src/server/index.js
  src/server/init.js
  src/server/routes/router.js
Labels: automated tests, backend

#33 #31 CI pipeline tests coverage check
  .circleci/config.yml
  .gitignore
  src/server/.tests/utilities.spec.js
  src/server/package-lock.json
  src/server/package.json
  src/server/utilities.js
Labels: automated tests, backend

#41 #40 #43 #46 Listing members of room
  .vscode/launch.json
  src/server/.eslintrc.json
  src/server/.tests/gitSyncer/GitListener.spec.js
  src/server/.tests/gitSyncer/GitWebHookMocker.js
  src/server/.tests/gitSyncer/dummyGitHookMessage.json
  src/server/.tests/passport/strategies.spec.js
  src/server/.tests/passport/strategyUtils.spec.js
  src/server/.tests/ws-routes/controllers/Room.spec.js
  src/server/gitSyncer/GitListener.js
  src/server/gitSyncer/gitMessages.js
  src/server/gitSyncer/index.js
  src/server/init.js
  src/server/package-lock.json
  src/server/package.json
  src/server/passport/strategies.js
  src/server/passport/strategyUtils.js
  src/server/protocol/protocol.json
  src/server/ws-routes/controllers/Room.js
Labels: PRIORITY, backend, documentation, enhancement

#60 #34 Serving protocol over HTTP
  src/server/routes/router.js
Labels: WIP, backend, enhancement

#65 Added tests for callbacks
  src/client/src/.tests/components/chatpage.test.js
  src/client/src/components/chatpage.js
  src/client/src/index.js
Labels: automated tests, frontend

#70 Startup fix
  src/client/src/App.js
  src/client/src/index.js
Labels: PRIORITY, bug, frontend

#76 #73 chatpage fix
  src/client/package-lock.json
  src/client/package.json
  src/client/src/.tests/components/chatpage.test.js
  src/client/src/App.js
  src/client/src/components/chatpage.js
Labels: PRIORITY, bug, frontend, release blocker

#66 #48 Automated ws testing tool configuration accoridng to protocol.json
  src/server/.tests/tools/.eslintrc.json
  src/server/.tests/tools/webSocketsTester.css
  src/server/.tests/tools/webSocketsTester.html
  src/server/.tests/tools/webSocketsTester.js
Labels: backend

#77 #75 Eslint frontend hotfix
  src/client/.eslintrc.json
  src/client/src/.eslintrc.json
  src/client/src/.tests/components/chatpage.test.js
  src/client/src/components/chatpage.js
  src/client/src/components/register.js
Labels: bug, devOps, frontend

#83 #82 Broadcasting listUsers to everyone in the room
  src/server/.tests/ws-routes/controllers/Room.spec.js
  src/server/ws-routes/controllers/Room.js
Labels: PRIORITY, backend, bug, release blocker

#64 #22 #16 config validation and generation
  .circleci/config.yml
  .gitignore
  src/server/.tests/configFileService.spec.js
  src/server/.tests/e2e/applicationRun.spec.js
  src/server/configFileService.js
  src/server/dbConnection.js
  src/server/index.js
  src/server/init.js
  src/server/logger.js
  src/server/miscellaneous/configErrorMessages.json
  src/server/miscellaneous/templateConfig.json
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/router.js
Labels: backend, enhancement

#78 #37 Users searching
  src/server/.tests/utilities.spec.js
  src/server/.tests/ws-routes/controllers/Room.spec.js
  src/server/.tests/ws-routes/controllers/Users.spec.js
  src/server/protocol/protocol.json
  src/server/utilities.js
  src/server/ws-routes/controllers/Room.js
  src/server/ws-routes/controllers/Users.js
  src/server/ws-routes/webSocketRouting.js
Labels: backend, enhancement
