Repository michaelKurowski/lokim2, pull requests merged in 2019-04, with the labels that each got.

#163 #162 CI failing during installing dependencies for Cypress
  .circleci/config.yml
Labels: bug, devOps

#161 #135 Single command to build project
  README.md
  package.json
  src/server/frontEnd/package-lock.json
  src/server/package-lock.json
Labels: devOps, documentation, enhancement

#165 #51 Make LokIM build commands OS agnostic
  .circleci/config.yml
  .gitignore
  Procfile
  README.md
  gulpfile.js
  package-lock.json
  package.json
  src/server/.tests/mocha/generate-docs.spec.js
  src/server/.tests/mocha/ws-routes/controllers/Room.spec.js
  src/server/connectToDb.js
  src/server/frontEnd/package-lock.json
  src/server/frontEnd/package.json
  src/server/package-lock.json
  src/server/package.json
Labels: WIP, devOps

#171 #170 Remove codecov blocking ability
  codecov.yml
Labels: devOps

#176 #175 fix failing frontend tests
  .circleci/config.yml
  .gitignore
  README.md
  package-lock.json
  src/server/frontEnd/package-lock.json
  src/server/frontEnd/package.json
  src/server/frontEnd/src/.tests/theme/scenes/chatpage.spec.js
  src/server/package-lock.json
  src/server/package.json
Labels: bug

#183 #136-cypress-doesn't-work-locally
  README.md
  src/server/frontEnd/package-lock.json
  src/server/package-lock.json
Labels: bug, devOps

#184 #182 Changed gulpfile.js to use npm ci instead of npm install.
  gulpfile.js
Labels: devOps
